name: Build + Push + Deploy ITMO Counter

on:
  push:
    branches: [ "master" ]

jobs:
  book-library-frontend-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'not_empty'
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Login to server
        run: ssh -T root@${{ secrets.SSH_HOST }} exit
      - name: Build Docker image
        run: docker compose build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Counter Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/itmo-counter;
      - name: Push Postgres Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/itmo-postgres;
      - name: Deploy to server
        run: >
          ssh -T root@${{ secrets.SSH_HOST }} "docker ps -aq | xargs docker stop | xargs docker rm;
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/itmo-counter;
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/itmo-postgres;
          docker run -e POSTGRES_DB=counter_info -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 ${{ secrets.DOCKERHUB_USERNAME }}/itmo-postgres;
          docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/itmo-counter;
          exit"
